# Generated by Django 4.1.2 on 2022-11-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0007_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
