# Generated by Django 4.1.2 on 2022-11-28 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0009_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
