# Generated by Django 4.1.2 on 2022-11-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0010_rename_category_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('phone', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
